services:
  postgres:
    image: pgvector/pgvector:pg17
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:?error}
      POSTGRES_DB: rubber_ducky
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: on-failure:0

volumes:
  postgres_data:
